### ISSUE TITLE
getSentry

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/temii#100]
- [x] Crear cuenta en getsentry
- [ ] Integrar con canal de discord

**Comment by javierdaza** [comment]
Resuelto parcialmente en https://github.com/PyBAQ/temii/pull/117 y https://github.com/PyBAQ/temii/pull/118

**Comment by pyjavo** [comment]
No se puede integrar con discord. Solo está disponible para "team billing plans and above"
https://docs.sentry.io/product/integrations/notification-incidents/discord/
