### ISSUE TITLE
Documentación como instalarlo

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/temii#102]
- [ ] Crear la documentación sobre como instalar el proyecto localmente. Este issue esta relacionado con el #14 
- [ ] Agregar enlace a http://python-social-auth-docs.readthedocs.io/en/latest/backends/meetup.html para generar keys de meetup en entorno local

**Comment by Scot3004** [comment]
Creo que queda aun mejor si se agrega información de como crear el virtualenv con pyenv

**Comment by Scot3004** [comment]
No pude correrlo con pyenv 😭, corrio con docker 😅, documentarlo resolveria este issue, o es un issue nuevo?

**Comment by javierdaza** [comment]
Como no estamos hablando de docker implicaría un nuevo issue. Debería correr con pyenv, de hecho es más fácil que docker

**Comment by javierdaza** [comment]
Aunque quedaría más como una propuesta tuya que como un "issue" porque aún no hemos hablado de pasarnos a Docker jejeje y tampoco creo que sea convierta en un requisito para sacar la versión Beta @Scot3004

**Comment by Scot3004** [comment]
bueno, lo intentare de nuevo, y si, tambien lo pense como algo opcional, ya que instalar docker es mamon, lo que tambien es cierto que el que tiene ya docker, le sale mas facil escribir docker-compose up y que el solito haga todo
