### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/temii#14]
Debe haber una documentación tanto para el archivo README.md como para CONTRIBUTORS.md

**Comment by fcartu** [comment]
Yo puedo aportar con **CONTRIBUTORS.md**, creo que es importante definir estandares de desarrollo, configuración de editores o IDEs con soporte a PEP8.

**Comment by pyjavo** [comment]
Se cierra el Issue por ser muy antiguo.
