### ISSUE TITLE
Postular charla

### ISSUE THREAD

**Issue by bgarcia92** [PyBAQ/temii#140]
Se debe permitir registrar la charla de un ponente con los siguientes datos:

1. E-mail
2. Nombre completo
3. Número de teléfono
4. Título tentativo de la charla
5. Biografía
6. Descripción
7. Fotografía (pegar la URL)
8. Mes(es) de la charla
9. Nivel(principiante, intermedio, avanzado)
10. Idioma
11. Comentario
12. Usuario de github/gitlab

**Comment by kary1806** [comment]
Flujo de la aplicacion 

1. Pantalla ingresar email y usuario
2. Pantalla de listado de eventos
3. Cada evento tendra una pantalla con su listado de charlas  (donde el usuario podra votar por la charla)

**Comment by kary1806** [comment]
Modelos para el proyecto 

1. Charlas
    Titulo
    Archivos
    Fotografia de la charla
    Nombre completo del orador
    Email del orador
    Descripción
    Fotografía (pegar la URL) del orador
    Mes(es) de la charla
    Nivel(principiante, intermedio, avanzado)
    Idioma
    Comentario
    Usuario de github/gitlab del orador
  
2. Eventos
    Nombre del evento
    Fecha limite
    Charlas ( todas las charlas relacionada a este evento)
    
3. Votaciones
    Nombre del votante
    Email del votante
    evento - relacion con la tabla evento
    charla - relacion con la charla

**Comment by pyjavo** [comment]
¡Super @kary1806!
Lo único que me llama la atención es que habíamos hablado de ahora hacer las votaciones en cada red social https://github.com/PyBAQ/temii/issues/148

Por lo que creo que ese modelo como está debería cambiar.

Ahora, hay algo nuevo que propongo que tengamos en consideración y es que las votaciones deberían ser opcionales. Hay 2 escenarios que recuerdo que han ocurrido:

1. Hay ponentes que tienen varios temas disponibles y no saben por cual decidirse, entonces es en ese caso sometemos los temas a votación
2. Aplican múltiples ponentes el mismo mes y no sabemos cuál tema escoger. entonces dejamos que la gente escoja

El escenario normal es que un ponente propone solo 1 tema y ese es el que se escoge como charla del mes

**Comment by kary1806** [comment]
@pyjavo el escenario no es para un oponente todos los que quiera, la persona puede crear las dos charlas y colocarla en evento para que se haga las votaciones

**Comment by pyjavo** [comment]
Resueltos por PR #209 y #217
