### ISSUE TITLE
Add env/ to .gitignore file

### ISSUE THREAD

**Issue by CamilaPua** [PyBAQ/temii#241]
# Solicitud de mejora en Temii

Solo se debe agregar `env/` al archivo .gitignore

## Ventajas

Evita que un contribuidor cargue por error su entorno virtual.

## Desventajas

Ninguna, pero ¿cómo podemos evitar que los contribuidores carguen su entorno virtual si tiene un nombre distinto a los del archivo .gitignore?

**Comment by Scot3004** [comment]
En cuanto a la pregunta hecha en las desventajas, en estos momentos tenemos adicionados los siguientes posibles nombres:

# Environments
.venv
venv/
ENV/

por lo general yo creo mis virtual environments con el comando `python -m venv venv` pero si hay otro esquema de nombres que uses para los tuyos puedes agregarlo

**Comment by CamilaPua** [comment]
yo solo uso env/ pero he visto tutoriales donde llaman al entorno distinto, ejemplo: myenv/ y cosas así bien lokas jaja
