### ISSUE TITLE
Scripts para minificar Scripts y CSS

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/temii#63]
Puede ser gulp o grunt para unir y minificar los css y javascript de la aplicación

**Comment by javierdaza** [comment]
@Scot3004 que me dices de Bower? Creo que bower tambien podriamos usarlo y se podria hacer otro issue para ello

**Comment by Scot3004** [comment]
#99 usando django assets da respuesta a este issue, respecto a bower es otro issue

**Comment by javierdaza** [comment]
@Scot3004 Bower me parece que es una buena opción

**Comment by GudarJs** [comment]
Sería mejor webpack o un script en JS.

Por: la gente de Bower pide que se use webpack cuando lo descargas por npm

**Comment by javierdaza** [comment]
Supuse que dirían algo. Ok, webpack. Ya sabemos quien es el experto ( @Scot3004  )

**Comment by Scot3004** [comment]
Si, los de bower recomiendan yarn con webpack e.e
