### ISSUE TITLE
Gestión de dependencia javascript

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/temii#64]
Se puede gestionar las dependencias en javascript usando bower

**Comment by Scot3004** [comment]
Despues de un buen analisis, npm en si ofrece muy buenas prestaciones para la gestión de dependencias en front-end

**Comment by javierdaza** [comment]
@Scot3004 por favor comparte el análisis. ¿Por qué NPM sobre bower?

**Comment by Scot3004** [comment]
Escribí un post en mi blog con el análisis
https://www.scot3004.xyz/2016/06/18/por-que-uso-npm.html
