### ISSUE TITLE
Resaltar mejor la forma como aparece la charla agendad en la vista index

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/temii#79]
Posible mejora en el UX/UI de la vista index
- [ ] Quitar el subrayado azul por una separación de las charlas
- [ ] Tal vez colocar el icono de un color diferente cuando la charla este agendada

**Comment by leonardoo** [comment]
si ese subrayado azul esta bn horrible, lo hice de rapidez, para que alguien lo modificara en un futuro cercano
