### ISSUE TITLE
Votar por un tema

### ISSUE THREAD

**Issue by javierdaza** [PyBAQ/temii#8]
Las personas puedan votar por una tema en particular que quieran que se convierta en charla (esto hace referencia a los temas posibles)

Solo se permite un voto por tema. Los usuarios pueden votar por todos los temas que quieran

**Comment by Scot3004** [comment]
Eso solo seria en los posibles temas a dictar

**Comment by leonardoo** [comment]
@Scot3004 solo se podra votar en los temas posibles

**Comment by javierdaza** [comment]
Segun sugerencia de @leonardoo esto se puede resolver usando:

1. **get or create** en la vista
2. Ajax en el front end

**Comment by Scot3004** [comment]
Creo que puedo hacer algo interesante usando esto, de hecho consulto a ver si dan luz verde
[https://github.com/Beeblio/django-vote]

**Comment by Scot3004** [comment]
Y esta otra dependencia podria ayudar
[https://github.com/eldarion/eldarion-ajax]

**Comment by javierdaza** [comment]
No implementes django-vote. Estabamos usando eldarion-ajax pero no terminamos de hacerla, adelante @Scot3004

**Comment by javierdaza** [comment]
Closed by 4cc00c4fc81a6e3aa45b79d8cc6cd8558d90ab4b

**Comment by javierdaza** [comment]
Este issue aún le falta

**Comment by Scot3004** [comment]
Esto es lo que está haciendo  @GudarJs o ya esta listo?

**Comment by javierdaza** [comment]
Si @Scot3004

**Comment by javierdaza** [comment]
mmmm aunque pensandolo bien, lo que hace @GudarJs es un issue relacionado con este

**Comment by Scot3004** [comment]
si, el hace algo sobre las estrellas, y es lo que le falta a este issue para cerrarse

**Comment by GudarJs** [comment]
Si es en este en el que estoy trabajando

**Comment by javierdaza** [comment]
Pongamosle una fecha @GudarJs ¿te parece?

**Comment by GudarJs** [comment]
si claro, podemos ponerlo para el lunes 10
